I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 20, in script
    define ps2 = Character("пасхалко2", callback=c_chan_voice, color="#FFFFFF")
  File "game/script.rpy", line 20, in <module>
    define ps2 = Character("пасхалко2", callback=c_chan_voice, color="#FFFFFF")
NameError: name 'c_chan_voice' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 20, in script
    define ps2 = Character("пасхалко2", callback=c_chan_voice, color="#FFFFFF")
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 2222, in execute
    self.set()
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 2236, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 20, in <module>
    define ps2 = Character("пасхалко2", callback=c_chan_voice, color="#FFFFFF")
NameError: name 'c_chan_voice' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
code tyan 1.0
Thu Jan 16 16:56:37 2025
