I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 205, in script
    with issolve(2.0)
  File "game/script.rpy", line 205, in <module>
    with issolve(2.0)
NameError: name 'issolve' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 205, in script
    with issolve(2.0)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 1356, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 205, in <module>
    with issolve(2.0)
NameError: name 'issolve' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
code tyan 1.0
Sun Mar 23 18:18:13 2025
